export const LevelConfig = Object.freeze([
  {
    cells: [
      { score: 1 },
      { score: 2 },
      { score: 3 },
      { score: 2 },
      { score: 1 },
      { score: 1 },
      { score: 2 },
      { score: 2 },
      { score: 3 },
      { score: 1 },
      { score: 3 },
      { score: 2 },
      { score: 1 },
      { score: 2 },
      { score: 1 },
      { score: 3 },
      { score: 2 },
      { score: 2 },
      { score: 3 },
      { score: 2 },
      { score: 1 },
      { score: 2 },
      { score: 2 },
      { score: 1 },
      { score: 2 },
      { score: 3 },
      { score: 1 },
      { score: 2 },
    ],
  },
]);
